Hypothesis testing and generator improving
ArtemiyGranat/brute pull request #12
Opened 2023-10-07 11:59 UTC by ArtemiyGranat

2023-10-09 22:08 UTC, ArtemiyGranat commented
Added clang checks on ubuntu and valgrind found some troubles in code. Will fix them tomorrow. 

MacOS check failed because of `crypt` port. Will try to fix it tomorrow too.

2023-10-18 15:57 UTC, hnarkaytis requested changes

2023-10-18 15:57 UTC, hnarkaytis commented on main.c
> +	      config->brute_mode = BM_REC_GEN;
extra indent

2023-10-18 15:57 UTC, hnarkaytis commented on rec.c
> +  swapcontext (&state->contexts[0], &state->contexts[1]);
canceled also needs to be checked before context swap. No need to to iterate if iterator is finished.

2023-10-18 19:59 UTC, ArtemiyGranat commented
Fixed MacOS bruteforce by porting `crypt` lib from musl libc. Now only performance tests on each OS (and valgrind test on Ubuntu with clang) are failing.

2023-10-18 22:44 UTC, hnarkaytis requested changes

2023-10-18 22:44 UTC, hnarkaytis commented on rec.c
> +    swapcontext (&state->contexts[0], &state->contexts[1]);
swapcontext might return an error.

2023-10-18 22:44 UTC, hnarkaytis commented on rec.c
> +  swapcontext (&state->contexts[0], &state->contexts[1]);
swapcontext might return an error.

2023-10-18 22:44 UTC, hnarkaytis commented on rec.c
> +  getcontext (&state->contexts[0]);
getcontext might return an error.

2023-10-18 22:44 UTC, hnarkaytis commented on rec.c
> +  swapcontext (&state->contexts[1], &state->contexts[0]);
swapcontext might return an error.

2023-10-19 17:12 UTC, hnarkaytis requested changes
Try -gdwarf-4 instead of -ggdb3

2023-10-19 17:25 UTC, hnarkaytis approved these changes
LGTM

2023-10-19 17:25 UTC, ArtemiyGranat commented
> Try -gdwarf-4 instead of -ggdb3

It worked, thank you! Performance tests sometimes fail in macOS, but I use my `crypt` port and the semaphore implementation in Linux too, maybe it's something with `macos-latest` in GH Actions, haven't figured it out yet. Should I run performance tests in Github Actions?

2023-10-19 17:27 UTC, ArtemiyGranat commented
> > Try -gdwarf-4 instead of -ggdb3
> 
> It worked, thank you! Performance tests sometimes fail in macOS, but I use my `crypt` port and the semaphore implementation in Linux too, maybe it's something with `macos-latest` in GH Actions, haven't figured it out yet. Should I run performance tests in Github Actions?

I mean Github Actions job in `macos-latest`, on my laptop everything works fine.

2023-10-19 17:32 UTC, hnarkaytis commented
Macos on github is flaky with performance tests. I skip performance tests on all virtual platforms.
https://github.com/alexanderchuranov/Metaresc/blob/3c4e281f7d29d8bba4ace4fff9bfecdf5c604840/.github/workflows/test.yml#L43

2023-10-19 17:43 UTC, ArtemiyGranat commented
> Macos on github is flaky with performance tests. I skip performance tests on all virtual platforms. https://github.com/alexanderchuranov/Metaresc/blob/3c4e281f7d29d8bba4ace4fff9bfecdf5c604840/.github/workflows/test.yml#L43

Ok, added `WITH_PERF_TEST` variable to Makefile.

2023-10-19 17:47 UTC, merged