Multi threaded bruteforce
ArtemiyGranat/brute pull request #8
Opened 2023-08-24 13:47 UTC by ArtemiyGranat

I think I will rename `my_sem_X` to `sem_X`, move it to `semaphore.h` file and add `include` based on OS if my semaphore implementation is correct.

Something like:
```
#ifdef __APPLE__
#include "semaphore.h"
#else
#include <semaphore.h>
#endif
```

2023-08-24 14:26 UTC, hnarkaytis commented on main.c
> +  pthread_cond_signal (&sem->cond_sem);
Signalling is an expensive kernel call. It make sense to make it only if counter was 0 before increment.

2023-08-24 14:28 UTC, hnarkaytis commented on main.c
> +void
Error code

2023-08-24 14:28 UTC, hnarkaytis commented on main.c
> +void
Error code

2023-08-24 19:59 UTC, ArtemiyGranat commented on main.c
> +void
Should I add messages to errors in `queue_X` functions?
Like `fprintf (stderr, "Could not initialize semaphore");`

2023-08-25 15:51 UTC, hnarkaytis requested changes
One more minor error check and this could be merged.

2023-08-25 15:51 UTC, hnarkaytis commented on main.c
> +  pthread_mutex_unlock (&sem->mutex);
error check?

2023-08-25 23:15 UTC, hnarkaytis approved these changes
LGTM

2023-08-25 23:15 UTC, merged